language: java
jdk: oraclejdk8

install: ./gradlew setupCIWorkspace -S
script:
 - ./gradlew build -S
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

after_success:
 - export LATEST_JAR="`ls -t build/libs/*.jar | grep -v sources | head -1`"
 - export TARGET_NAME="`basename $LATEST_JAR`"
 - ./dropbox_uploader.sh upload $LATEST_JAR $TARGET_NAME

env:
  global:
    TERM=dumb

sudo: false

cache:
  directories:
    - ./libs
    - $HOME/.gradle/caches
