
name: Build Information (Last Tag)
on: workflow_dispatch

jobs:
  info:
    name: Info
    runs-on: ubuntu-20.04
    outputs:
      release_type: ${{steps.cf_release_type.outputs.value }}
      cf_project: ${{steps.cf_project.outputs.value }}
      mod_id: ${{steps.mod_id.outputs.value }}
      version: ${{steps.version.outputs.value }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Release Type
        id: cf_release_type
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'cf_release_type'

      - name: Project ID
        id: cf_project
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'cf_project'

      - name: Mod ID
        id: mod_id
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'mod_id'

      - name: Find Current Tag
        id: current
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: '@'
          skip-unshallow: 'true'

      - name: Semver Version
        id: version
        run: |
          id=$(echo ${{steps.current.outputs.value}} | cut -d=v -f2)
          echo "::set-output name=id::$id"