name: Build with Gradle (Semver Releases)

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew build

      - name: Add Artifact
        uses: actions/upload-artifact@v2
        with:
          name: libs
          path: build/libs/*.jar

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Results
        uses: actions/download-artifact@v2
        with:
          name: libs
          path: buildfiles

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "Release ${{ github.event.release.tag_name }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            CHANGELOG.txt
            LICENSE.txt
            buildfiles/*