name: Test Build and Changelog

on:
  workflow_dispatch:

jobs:
  changelog:
    name: Generate Changelog (tags)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Find Current Tag
        id: current
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: '@'
          skip-unshallow: 'true'

      - name: Previous Tag
        id: last
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: ${{steps.current.outputs.tag}}
          skip-unshallow: 'true'

      - name: Generate changelog
        uses: jimschubert/beast-changelog-action@v1
        with:
          GITHUB_TOKEN: ${{github.token}}
          CONFIG_LOCATION: .github/changelog.json
          FROM: ${{steps.last.outputs.tag}}
          TO: ${{steps.current.outputs.tag}}
          OUTPUT: .github/CHANGELOG.md

      - name: Read CHANGELOG file
        id: getchangelog
        run: echo "::set-output name=changelog::$(cat .github/CHANGELOG.md)"

      - name: View Changelog
        run: cat .github/CHANGELOG.md

      - name: Add Artifact
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: .github/CHANGELOG.md

  jar:
    name: Publish JAR
    runs-on: ubuntu-latest
    needs: [changelog]
    steps:
      - name: Download Changelog Results
        uses: actions/download-artifact@v2
        with:
          name: out
          path: changelog

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR with Gradle
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Artifact
        uses: actions/upload-artifact@v2
        with:
          name: libs
          path: build/libs/*.jar

  echo:
    name: Echo Variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release Type
        id: releasetype
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'cf_release_type'

      - name: Echo
        run: echo ${{steps.releasetype.outputs.value }}

  view:
    name: View Changelog Output
    runs-on: ubuntu-latest
    needs: [changelog]
    steps:
      - name: Download Build Results
        uses: actions/download-artifact@v2
        with:
          name: out
          path: changelog
      - run: cat changelog/CHANGELOG.md
